services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
    - POSTGRES_USER=local_user
    - POSTGRES_DB=food
    - POSTGRES_PASSWORD=local_password
    ports:
      - "5432:5432"